
version: '3'
services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile-dev
    ports:
      - "8080:3306"
    container_name: back
    volumes:
       - ./back:/usr/src/app/back
       - /usr/src/app/back/node_modules
